### ISSUE TITLE
How to disable ssl verification for external object storage

### ISSUE THREAD

**Issue by rosh0450** [quay/quay-operator#1015]
Here's my config.yaml

```
# unmanaged storage: netapp-ontap
# link: https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/configure_red_hat_quay/index#config-fields-netapp-ontap
DISTRIBUTED_STORAGE_CONFIG:
  local_us:
    - RadosGWStorage
    - access_key: ******
      bucket_name: bucket-quay
      hostname: abc.s3.com
      is_secure: true
      port: 443
      secret_key: *******
      storage_path: /datastorage/registry
      signature_version: v4
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
  - local_us
DISTRIBUTED_STORAGE_PREFERENCE:
  - local_us
```

When I deploy the quay with this config, the pod: quay-app errors out with log
```
 DistributedStorage | Could not connect to storage local_us. Error: Get "https://abc.s3.com/bucket-quay/?location=": tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead | 🔴 |
```

So for my testing/development purpose how to skip the SSL verification??
