### ISSUE TITLE
Invalid DB volume size breaks deployment

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#102]
While verifying the persistent volume for Postgres, I accidentally specified an invalid unit of measure. The operator did not provide any useful log information as to why my Quay Ecosystem was not being deployed.

After correcting the unit of measurement and redeploying my CR, the ecosystem deployed successfully.

Example:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    database:
      volumeSize: 10gi  # This should be 10Gi
```
