### ISSUE TITLE
SUPER USER Not Propagating in Red Hat Quay v3.13.4

### ISSUE THREAD

**Issue by pr3sh** [quay/quay-operator#1028]
**Issue Summary**

I deployed Red Hat Quay v3.13.4 using the OperatorHub (fully managed) on OpenShift.
I was able to update `config.yaml` via the Quay Operator’s secret to allow pushing larger images, and the changes successfully propagated to the pods.

However, when I tried to add a superuser (`SUPER_USERS`), the change does not propagate to the running Quay pods, and my user is not granted superuser access.

📌 **Expected Behavior**
After adding `SUPER_USERS` in `config.yaml`, I expect my user (ikennapreciouschima) to be recognized as a superuser.
The update should be reflected inside the Quay pod configuration.
I should see the Superuser Panel in the Quay UI.

📌 **Actual Behavior**
The `SUPER_USERS` field appears correctly in the config secret:
```bash
oc extract secret/atom-quay-config-bundle-vqgn9 -n quay --to=./quay-config-check --confirm
cat ./quay-config-check/config.yaml | grep SUPER_USERS -A 5
```
Output:
```bash
FEATURE_SUPER_USERS: true
SUPER_USERS:
  - ikennapreciouschima
```
However, when checking the running Quay pods, `SUPER_USERS` is missing from the applied configuration:

```bash
oc exec -it atom-quay-quay-app-7864564649-8rprm -n quay -- cat /quay-registry/conf/stack/config.yaml | grep SUPER_USERS -A 5
```
Output:
(No SUPER_USERS field present)

📌 Steps to Reproduce
Deploy Red Hat Quay `v3.13.4` using the OperatorHub on OpenShift.
Extract and update the config secret (atom-quay-config-bundle-vqgn9):
```yaml
FEATURE_SUPER_USERS: true
SUPER_USERS:
  - ikennapreciouschima
```
Apply the updated secret and restart Quay pods.
Check the running pods to confirm if `SUPER_USERS` is present.
Attempt to access superuser features in the UI (not available).
📌 Additional Information

- Full Config File

```yaml
# Superuser Configuration
FEATURE_SUPER_USERS: true
SUPER_USERS:
  - ikennapreciouschima

# General Authentication and Access Control
ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: Database
FEATURE_DIRECT_LOGIN: true
FEATURE_MAILING: false

# Registry UI and Branding
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg

# Tag Expiration and Synchronization Settings
DEFAULT_TAG_EXPIRATION: 2w
TAG_EXPIRATION_OPTIONS:
  - 2w
TEAM_RESYNC_STALE_TIME: 60m

# Quay Feature Toggles
FEATURE_BUILD_SUPPORT: false
FEATURE_LARGE_BLOBS: true
TESTING: false
SETUP_COMPLETE: true

# Large Image Upload Configuration
DISTRIBUTED_STORAGE_CONFIG:
  default:
    - RHOCSStorage
    - {
        storage_path: "/datastorage/registry",
        chunk_size: "52428800"
      }

LARGE_BLOB_STORAGE_THRESHOLD: 52428800
PUSH_TEMP_STORAGE_EXPIRATION: 3600
```
