### ISSUE TITLE
Unable to configure OIDC (Unclear error and unexpected behavior)

### ISSUE THREAD

**Issue by soubinan** [quay/quay-operator#1032]
Hello,

I am wondering what is missing in my OIDC config to make it work... I followed the documentation and I do not have a clue of issue reason.

Error when validating the OIDC config
```sh
+------------------------+--------------------------------------------------------------------------------------------+--------+
| LDAP | - | 🟢 |
+------------------------+--------------------------------------------------------------------------------------------+--------+
| OIDC | Could not reach OIDC server zitadel. Error: oauth2: "invalid_request" "Errors.User.Code.Invalid" | 🔴 |
+------------------------+--------------------------------------------------------------------------------------------+--------+
| QuayDocumentation | - | 🟢 |
+
```

My QuayRegistry config
```yaml
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-registry
spec:
  components:
    - kind: clair
      managed: true
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: tls
      managed: true
    - kind: quay
      managed: true
    - kind: clairpostgres
      managed: true
  configBundleSecret: quay-registry-config-bundle
```

My bundle secret config content: quay-registry-config-bundle
```yaml
SERVER_HOSTNAME: quay-registry.apps.foo.baz
ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: OIDC
ZITADEL_LOGIN_CONFIG:
  CLIENT_ID: "314045226417218573"
  CLIENT_SECRET: akfIHMZz1gMELzfPXkiEBbU3jnJtgni1Z00NykSrp4KUY5b3a1cjYs1nrZMiwLyM
  OIDC_SERVER: https://iam.foo.baz/
  OIDC_ISSUER: https://iam.foo.baz/
  SERVICE_NAME: zitadel
  LOGIN_SCOPES: ["openid", "email", "profile"]
SETUP_COMPLETE: true
SUPER_USERS: ["quayadmin"]
```

My config on OIDC server side

![Image](https://github.com/user-attachments/assets/e23e50fc-289c-4da1-a12d-96ad686064f8)

And the redirect URLs below:
```
https://quay-registry.apps.foo.baz/oauth2/zitadel/callback
https://quay-registry.apps.foo.baz/oauth2/zitadel/callback/cli
https://quay-registry.apps.foo.baz/oauth2/zitadel/callback/attach
```

I do not see what I missed there, based on the documentation all is as expected, but it is not working
I have many other applications set on the OIDC provider, and it is the first behaving that way
One thing I noticed is that the OIDC documentation is specific to Azure Entra ID and RedHat SSO/Keycloak, but I assume it is not compatible only with them.
