### ISSUE TITLE
Postgres for Clair is not deployed if existing DB is used for Quay

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#111]
While testing 0.0.8, it was discovered that using a CR to manually specify an existing Postgres for Quay stops the operator from deploying a Postgres database for Clair.

If this is the intended behaviour, it may be a matter of updating the documentation.

**Expected Behavior:**
- Postgres is deployed for Clair

**Actual Behavior:**
- No postgres is deployed.

**Example CR**
```
spec:
  quay:
    database:
      credentialsSecretName: postgresql-account
      server: 172.30.98.48:5432
  clair:
    enabled: true
    imagePullSecretName: quay.io
    database:
      volumeSize: 3Gi
```
