### ISSUE TITLE
nodeSelector fails to validate

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#112]
During testing of 0.0.8, it was found that specifying the `nodeSelector` failed to validate successfully.

According to those who performed the testing, the expected result was that the Quay ecosystem would deploy successfully. 

The observed behaviour was the following error:
```
The QuayEcosystem "quay-test-320" is invalid: []: Invalid value: map[string]interface {} : validation failure list:
spec.quay.nodeSelector in body must be of type object: "string"
```

Example CR:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    nodeSelector:
      role=node
```

It's possible that this may simply require a documentation enhancement if the `nodeSelector` was specified incorrectly.
