### ISSUE TITLE
Incorrect README examples

### ISSUE THREAD

**Issue by windmark** [quay/quay-operator#173]
Hi,

First of all thank you for a create operator in general. However, there seems to be many cases where the README examples of configurations don't correspond to the actual CRD. Comparing the [QuaEcosystem CRD](https://github.com/redhat-cop/quay-operator/blob/211d65c293ff6f0fdeab39fe28d37b82d6affcef/deploy/olm-catalog/quay/1.0.2/redhatcop.redhat.io_quayecosystems_crd.yaml) with the examples, the major discrepancy seems to be the key `externalAccess` which I can't find in the yaml. This means that for example the case in the README with

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    externalAccess:
      tls:
        secretName: custom-quay-ssl
````
rather should be

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    sslCertificatesSecretName: custom-quay-ssl
```

The same applies to the hostname and probably more cases.
