### ISSUE TITLE
Operator is not Adding SUPER_USERS to Geo-replicated Quay instance

### ISSUE THREAD

**Issue by JuozasA** [quay/quay-operator#174]
I am using Operator 1.0.2 for both Quay 3.2 instances on separate OCP 4.3 clusters. 

1st Quay instance gets deployed successfully (when the database is empty), but when I use Operator for 2nd Quay deployment, it skips super user creation (because user already exists in the shared database) but with that, it is not adding SUPER_USERS field into Quay config.yaml so after deployment is finished, 2nd Quay instance does not have Super User Admin Panel in the GUI and also, clair security-scanner secret is not being created (even if clair is not sharing the database) on the 2nd instance. 

Would be good if operator would check if super user already exists in the database and populate those fields into config.yaml and create security scanner secret if one does not exist

**Comment by ibazulic** [comment]
If you deploy Quay instances in two separate locations but you want them to work in georeplication mode, you have to have **the same** configuration on both places. Additionally:

- you need to have a unique entrypoint for all Quay instances/clusters for auth to work
- all instances need to have access to all storage engines
- all instances need to have access to the same database

All these requirements are satisfied **IF and only IF** setup is done on one location and then that config.yaml file is copied to all other locations. You cannot deploy Quay on the 2nd location from scratch.

**Comment by JuozasA** [comment]
I understand that, I am fine with copying the quay and clair configs, security_scanner private key to another cluster, but I would still want to use Operator for deploying other components like mirror pod and clair, but right now, if I set skipSetup: true, operator stops on quay deployment and will not progress with clair, or mirror deployments

**Comment by ibazulic** [comment]
Please see: 

https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploy_red_hat_quay_on_openshift_with_quay_setup_operator/customizing_your_red_hat_quay_cluster#injecting_configuration_files

**Comment by ibazulic** [comment]
Create a secret called quayconfig:

~~~
oc create secret quayconfig --from-file=/path/to/quay/config.yaml
~~~

Then, define the config file as follows:

~~~
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    configFiles:
      - secretName: quayconfig
~~~

Finally, add the `skipSetup: true` at the end. It should pull the config.yaml from the secret and mount it to the correct place in the pod.

**Comment by JuozasA** [comment]
So that mounts additional secret to quay deployment, but still ignores Clair and Mirroring deployment rollout:

My QuayEcosystem for 2nd:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay-enterprise
  namespace: quay-enterprise-apac
spec:
  clair:
    enabled: true
    updateInterval: 10m
    deploymentStrategy: RollingUpdate
    image: 'quay.io/redhat/clair-jwt:v3.2.1'
    database:
      credentialsSecretName: database-secret
      server: quay-database.example.com
    imagePullSecretName: redhat-pull-secret
  quay:
    configFiles:
      - secretName: quay-enterprise-config-secret-replicated
    hostname: quay-enterprise.example.com
    resources:
      requests:
        memory: 1000Mi
    externalAccessType: Route
    keepConfigDeployment: true
    enableRepoMirroring: true
    deploymentStrategy: RollingUpdate
    envVars:
      - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
        value: azure-southeastasia
    image: 'quay.io/redhat/quay:v3.2.1'
    database:
      credentialsSecretName: database-secret
      server: quay-database.example.com
    imagePullSecretName: redhat-pull-secret
    configSecretName: quay-config-app
    skipSetup: true
  redis:
    hostname: redis-cache.example.com
    port: 6379
    credentialsSecretName: quay-redis-password
```
but it still skips all other steps (to deploy Clair and Mirror pods):
```
$ oc get pods
NAME                                           READY   STATUS    RESTARTS   AGE
quay-enterprise-quay-7885dd7678-zq64n          1/1     Running   0          108s
quay-enterprise-quay-config-6b5dc8669f-9msrg   1/1     Running   0          8m55s
quay-operator-6544574d6f-bgzt9
```
I suspect, since deployment verification is skipped, it skips everything else:
`{"level":"info","ts":1585910554.3676286,"logger":"controller_quayecosystem","msg":"Skipping Quay Deployment verification as setup marked as skipped"}`
