### ISSUE TITLE
Generated certificate does not match the hostname

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#176]
**Description**

When deploying Quay with the latest code in master to GKE with the following configuration:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    image: quay.io/projectquay/quay:latest
    imagePullSecretName: redhat-quay-pull-secret
    keepConfigDeployment: true
    externalAccess:
      hostname: example.com
      type: LoadBalancer
```
The hostname is forced to the IP Address of the `Service`. Attempting to override it as demonstrated in the documentation does not work.

This blocks the ability to use the Configuration Application because it attempts to validate the self-signed certificate and finds that it does not match the hostname.

**Steps to Reproduce**

- Deploy a Quay Instance. Keep the Config app running.
- Access the config app.
- Don't make any changes. Just click "Save Configuration".
- The Configuration App will complain that the certificate does not match the hostname.

**Acceptance Criteria**

- The Quay Config application should not fail when validating the generated certificate.
- The CR should be able to override the hostname.
- If a hostname is automatically assigned, such as a subdomain or IP address, and no certificate is supplied, then I would assume the self-signed certificate to be generated for the correct host. (Debatable)
