### ISSUE TITLE
Clair - There is no way to pass extra CA certificates to Clair pod

### ISSUE THREAD

**Issue by scouturier** [quay/quay-operator#179]
Currently, there is no documented ways to pass extra CA certificates to Clair pod, therefore if Quay is using a self-signed (with CA) certificate on it's route, Clair will not trust it unless the certificate is manually added to the Deployment.

Could be similar to the extraCaCert for quay:
```
  quay:
    configFiles:
      - secretName: quayconfigfile
        type: extraCaCert
```
