### ISSUE TITLE
As a user, I want to modify MAIL_DEFAULT_SENDER config secret in CR.

### ISSUE THREAD

**Issue by thomasmckay** [quay/quay-operator#18]
```
spec:
  quay:
    config:
      mailDefaultSender: name@example.com
```

This should change "MAIL_DEFAULT_SENDER" in the config secret and trigger redploy.
