### ISSUE TITLE
Superuser not being created

### ISSUE THREAD

**Issue by werne2j** [quay/quay-operator#205]
I added a superuser to my ecosystem but the user is not getting superuser permissions:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  quay:
    image: quay.io/redhat/quay:v3.2.1
    imagePullSecretName: redhat-quay-pull-secret
    superuserCredentialsSecretName: jim-superuser
    superusers:
      - jim
```
Looking in the config.yaml that is created and there is no superuser entry
```
SETUP_COMPLETE: true
SIGNING_ENGINE: gpg2
TAG_EXPIRATION_OPTIONS:
```
