### ISSUE TITLE
Clair database configuration

### ISSUE THREAD

**Issue by werne2j** [quay/quay-operator#214]
What is the correct way to point clair to a managed postgres database? 
I tried to follow the same steps as for Quay but clair still spun up a local postgres.

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  quay:
    ...
  clair:
    enabled: true
    database:
      credentialsSecretName: credentialsSecretName
      server: <postgres-server>
```
