### ISSUE TITLE
Undocumented assumptions / usage of external host names (?)

### ISSUE THREAD

**Issue by filip-nilsson-sr** [quay/quay-operator#222]
I'm trying to get Quay up and running in a Kubernetes cluster.

During my attempts I've encountered a problem where it seems like the Quay operator needs to access the external host name specified in the manifest during the setup. If I for example use a config like this:

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem-v110
  namespace: quay-enterprise
spec:
  quay:
    externalAccess:
      type: Ingress
      hostname: registry.k8s.example.com
      configHostname: registry-config.k8s.example.com
```
the operator will make requests to `https://registry-config.k8s.example.com/api/v1/superuser/registrystatus` during the setup process.

This caused problems in my environment where I'm behind a firewall and those outgoing requests from the cluster wasn't allowed. I could still access it fine from outside the cluster, as the firewall allowed that, but could not proceed with the setup, since they failed like this: `Warning Failed to Setup Quay 64s  quayecosystem-controller Get https://registry-config.k8s.èxample.com/api/v1/superuser/registrystatus: dial tcp XXX.XX.XX.XXX:443: connect: connection timed out` (where the masked IP is my ingress controller).

Then I tried not setting the `configHostname`, hoping it would default to use the service cluster local hostname instead, but then I got this error instead: `Get https:///api/v1/superuser/registrystatus: http: no Host in request URL`

I got around it by setting the `configHostname` to `example-quayecosystem-v110-quay-config`, the service name generated by the operator. However, now I can't access the config web UI, since the ingress becomes miss configured.

Is it possible to separate the different hostnames as of now, forcing the operator to use the internal hostname? Otherwise I think it would be neat to allow both for external access with e.g an Ingress, but also exposing what hostname should be used for cluster-internal communication (and defaulting to the service created by the operator). Lastly, if this is not possible nor up for change, it might be nice to add some clarification about this in the docs, I didn't expect the operator needing to have external access to the registry.

Thanks for you great work with the operator!

**Comment by sabre1041** [comment]
@filip-nilsson-sr if you omit the `configHostname`, it should use the internal service. Would you be able to try this?

**Comment by filip-nilsson-sr** [comment]
@sabre1041: Yeah, that was what I tried (with "not setting" I meant to say "omitting" :)). 

I just double checked it again to be sure, it tries to access the URL `https:///api/v1/superuser/registrystatus`. From the operator pod log:
```
{"level":"error","ts":1589481923.3987017,"logger":"controller_quayecosystem","msg":"Failed to obtain initial registry status","error":"Get https:///api/v1/superuser/registrystatus: http: no Host in request URL","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/setup.(*QuaySetupManager).SetupQuay\n\t/home/runner/work/quay-operator/quay-operator/pkg/controller/quayecosystem/setup/setup.go:62\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem.(*ReconcileQuayEcosystem).Reconcile\n\t/home/runner/work/quay-operator/quay-operator/pkg/controller/quayecosystem/quayecosystem_controller.go:269\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

For completeness, this is the manifest:
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem-v110
  namespace: quay-enterprise
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    superuserCredentialsSecretName: quay-super-user
    configFiles:
      - secretName: example-enterprise-ca01
        type: extraCaCert
    configSecretName: quay-config-app
    externalAccess:
      type: Ingress
      hostname: registry.example.com
      tls:
        termination: passthrough
        secretName: example
      annotations:
         nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
         nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi
    database:
      credentialsSecretName: quay-database-credential
      server: database.example.com
  redis:
    imagePullSecretName: redhat-pull-secret
  clair:
    enabled: false
    imagePullSecretName: redhat-pull-secret
    updateInterval: "60m"
````
I'm using the `1.1.0`-tag version of the operator.
