### ISSUE TITLE
Redhat quay operator 3.3.0 fails to install due to bad csv

### ISSUE THREAD

**Issue by bfabec** [quay/quay-operator#241]
Attempting to install the redhat quay operator 3.3.0 fails on OCP 4.3 due to an invalid csv. Reviewing the failed install plan shows the following error:

```
  status:
    catalogSources:
    - redhat-operators
    conditions:
    - lastTransitionTime: 2020-06-04T20:02:09Z
      lastUpdateTime: 2020-06-04T20:02:09Z
      message: 'error creating csv red-hat-quay.v3.3.0: ClusterServiceVersion.operators.coreos.com
        "red-hat-quay.v3.3.0" is invalid: spec.customresourcedefinitions.owned.displayName:
        Required value'
      reason: InstallComponentFailed
      status: "False"
      type: Installed
    phase: Failed
```

Attaching the entire install plan log.
