### ISSUE TITLE
Unable to set configHostname with ingress externalAccess

### ISSUE THREAD

**Issue by HenriAW** [quay/quay-operator#252]
I am currently not able to provision quay using the ingress extrenalAccess type. Specifically when I include the configHostname value I receive the following error: `invalid character '<' looking for beginning of value`.

Running this without the configHostname gives me the following error: `quayecosystem-controller  Get https:///api/v1/superuser/registrystatus: http: no Host in request URL`, so I'm fairly sure this is something that needs to be set. If I use routes instead then quay will provision, however for this deployment we must use ingress. Any and all help would be appreciated.

Below is my quay-ecosystem config:
``` yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: {namespace}
spec:
  quay:
    enableRepoMirroring: true
    deploymentStrategy: Recreate
    imagePullSecretName: redhat-quay-pull-secret
    keepConfigDeployment: true
    envVars:
      - name: DEBUGLOG
        value: "true"
    skipSetup: false
    externalAccess:
      type: Ingress
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        kubernetes.io/ingress.class: "ingress-public"
      configAnnotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        kubernetes.io/ingress.class: "ingress-public"
      tls:
        secretName: "{tls_secret}"
        termination: passthrough
      hostname: "quay.{base_domain}"
      configHostname: "quayconfig.{base_domain}"
    registryBackends:
      - name: s3-backend
        credentialsSecretName: {iam-secret}
        replicateByDefault: false
        s3: 
          bucketName: "{bucket-name}"
          storagePath: "quay"
  clair:
    enabled: true
    imagePullSecretName: redhat-quay-pull-secret
    updateInterval: "60m"
```
