### ISSUE TITLE
External Access Ingress is missing tls.hosts 

### ISSUE THREAD

**Issue by p-v-a** [quay/quay-operator#259]
Hello,

Trying to deploy operator with TLS on, with the below declaration.
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: registry01
  namespace: quay-operator
spec:
  quay:
    superuserCredentialsSecretName: registry01-super-user
    configSecretName: registry01-config-app
    deploymentStrategy: RollingUpdate
    enableRepoMirroring: true
    skipSetup: false
    externalAccess:
      hostname: registry01.xxx.yyy.zzz
      configHostname: registry01-quay-config
      type: Ingress
      # here Quay operator fails short, it doesn't add hosts to the ingress tls section, thus cert-manager fails to autogenerate certificate
      annotations:
        ingress.kubernetes.io/affinity: cookie
        ingress.kubernetes.io/secure-backends: "true"
        cert-manager.io/issuer: ca-issuer
        cert-manager.io/issuer-kind: ClusterIssuer
``` 

When operator creates Ingress object it missing spec.tls.hosts, this causes cert-manager to fail with **"Warning  BadConfig  22m (x2 over 23m)  cert-manager        Secret "registry01-quay-ssl" for ingress TLS has no hosts specified"** in the event log of the ingress. I can see a way to disable self-signed cert generation, as just adding and adding annotations to ingress doesn't work, because of missconfig of the Ingress object, it would be good to have ability to control if user wants to use self-signed certificate, or use cert-manager for example

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: ca-issuer
    cert-manager.io/issuer-kind: ClusterIssuer
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/secure-backends: "true"
  labels:
    app: quay-operator
    quay-enterprise-component: app
    quay-enterprise-cr: registry01
  name: registry01-quay
  namespace: quay-operator
spec:
  rules:
  - host: registry01.xxx.yyy.zzz
    http:
      paths:
      - backend:
          serviceName: registry01-quay
          servicePort: 443
        path: /
  tls:
  - secretName: registry01-quay-ssl
  # However this section should be like this for cert-manager to issue certificate automatically:
  # - hosts:
  #     - registry01.xxx.yyy.zzz
  #   secretName: registry01-quay-ssl   
```
