### ISSUE TITLE
External access Openshift route annotation

### ISSUE THREAD

**Issue by siw36** [quay/quay-operator#310]
I'm using the Quay operator on Openshift and somehow need to limit the access to the Quay and Quay config routes to a list of IP addresses.
I tried to add the annotations to `spec.quay.externalAcccess.annotations` but it seems like this field is only relevant when the `externalAccess.type` is `ingress`.

Example:
```
[...]
    externalAccess:
      hostname: quay.apps.<domain>
      configHostname: quay-config.apps.<domain>
      annotations:
        haproxy.router.openshift.io/ip_whitelist: x.x.x.x,y.y.y.y
      tls:
        secretName: quay-letsencrypt-cert
        termination: passthrough
[...]
```
When I add annotations to the routes manually, the operator reverts that change at some point.

Is there a way to add annotations to the created Openshift routes?
