### ISSUE TITLE
PVC cannot be used for Quay Server

### ISSUE THREAD

**Issue by theodor2311** [quay/quay-operator#316]
## Description of the issue
Using PVC for the Quay server will result in permission denied on /datastorage/registry directory. Probably caused by upstream [quay/quay](https://github.com/quay/quay) no longer required root user.

## Version
OpenShift: 4.5.8
CSV: red-hat-quay.v3.3.2-20200903
Image: registry.redhat.io/quay/quay-rhel8-operator@sha256:98b9515f30976bacd3ccaec278c3a991ef64cfcdf8532c7b3bcf3c63f23d17ff

## Steps To Reproduce
Create QuayEcoSystem with PVC.
e.g
```yaml
spec:
  quay:	
    ...
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 200Gi
      ...
```
## Current Result
Quay server is using id 1001, which will have no permission writing to the pvc.
```bash
oc exec $(oc get pod -l quay-enterprise-component=app -o jsonpath='{.items[0].metadata.name}') -- id
uid=1001(default) gid=0(root) groups=0(root)

oc exec $(oc get pod -l quay-enterprise-component=app -o jsonpath='{.items[0].metadata.name}') -- /usr/bin/touch /datastorage/registry/test
/usr/bin/touch: cannot touch ‘/datastorage/registry/test’: Permission denied
```
## Workaround
~~Remove anyuid for the Quay service account.~~
Better to take @jfroment's approach by [setting fsGroup](https://github.com/quay/quay-operator/issues/316#issuecomment-696050212).

## Additional Information
Removing the rolebindings {quayecosystem-name}-scc for the Quay service account may fix this issue.
[Non-Root for Upstream Dockerfile PR](https://github.com/quay/quay/pull/363/files)

**Comment by jfroment** [comment]
I had the same issue.
Since the release of the Operator version 3.3.1, it is possible (but undocumented except in the issue tracker comments) to add an fsGroup to the "quay" object in your QuayEcosystem:

```yaml
quay:
  registryStorage:
    persistentVolumeAccessModes:
      - ReadWriteOnce
  securityContext:
    fsGroup: 1001
```

1001 being the user of the Quay Pod.
