### ISSUE TITLE
support minio as object storage

### ISSUE THREAD

**Issue by abdennour** [quay/quay-operator#380]
Quay requires object storage.
The documentation mentions:
- aws s3 
- openstack swift
- Or Ceph Rados ( l love OSDs btw)

Now the question, can you support customizing the endpoint of s3 api because i want to use minio.
While minio is 100% API compatible with AWS S3, i need to provide the endpoint (url) of the minio server

old similar issue : https://access.redhat.com/solutions/3782641

**Comment by alecmerdler** [comment]
Yes, MinIO will work with Quay using the `RadosGWStorage` driver option in `config.yaml` and providing the appropriate values. Our team has used it for development and testing purposes. It is _not_ supported as part of the Red Hat Quay product, however.

Here is a partial `config.yaml` for using MinIO:
```yaml
DISTRIBUTED_STORAGE_CONFIG:
  default:
  - RadosGWStorage
  - access_key: <hidden>
    secret_key: <hidden>
    hostname: <hidden>
    bucket_name: <hidden>
    port: 443
    is_secure: true
    storage_path: /datastorage/registry
```

**Comment by abdennour** [comment]
@alecmerdler  thank you so much! really appreciated!
Could you please do me a favor by sharing the file cconfiguration: not only config.yaml but also the kubernetes manifests (QuayRegistry/QuayEcosystem/ConfigMap/Secret/....) ? 
i just need the shape where you can hide irrelevant values (sensitive,.. so on)

**Comment by alecmerdler** [comment]
Sure, configuring a `QuayRegistry` to use unmanaged object storage should be very easy. You can either use the [config tool UI](https://github.com/quay/quay-operator/blob/master/docs/configuration.md#quay-config-editor) (found using `status.configEditorEndpoint`) or by providing `spec.configBundleSecret` which contains the required Quay config values found above. I won't go into deploying MinIO itself, but configuring Quay to use an existing MinIO deployment basically follows the ["unmanaged component" pattern](https://github.com/quay/quay-operator/blob/master/docs/components.md#component-config), which looks a bit like this:

**`whatever.quayregistryyaml`**
```yaml
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata: 
  name: whatever
spec:
  configBundleSecret: quay-config-abc
  components:
    - kind: objectstorage
      managed: false
```

**`quay-config-abc.secret.yaml`**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: quay-config-abc
stringData:
  config.yaml:
    ... <other key/values>
    DISTRIBUTED_STORAGE_CONFIG:
      default:
      - RadosGWStorage
      - access_key: <hidden>
        secret_key: <hidden>
        hostname: <hidden>
        bucket_name: <hidden>
        port: 443
        is_secure: true
        storage_path: /datastorage/registry
```
