### ISSUE TITLE
[Quay TNG] Unable to define a custom Route (+certificate) following documentation

### ISSUE THREAD

**Issue by jfroment** [quay/quay-operator#388]
Hello,

I'm having trouble setting up a custom Route with Quay TNG (both upgrading a Quay TNG and on a fresh install).
I followed your guide [here](https://github.com/quay/quay-operator/blob/master/docs/external-access.md), and now I have the following error in the Operators logs:

```
2021-01-28T15:18:52.283Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"QuayRegistry","namespace":"system-quay-registry-tng","name":"skynet","uid":"638ecf64-2327-4b07-9dc8-15040374f579","apiVersion":"quay.redhat.com/v1","resourceVersion":"489504949"}, "reason": "ConfigInvalid", "message": "clair component marked as managed, but `configBundleSecret` contains required fields"}
```

...and Deployments are stuck mid-rollout.

Here is the InstallPlan log:
```
error updating service: quay-operator: Service "quay-operator" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```

For information, I created the secret (referenced in the QuayRegistry CR below) like this in my CI script:

```sh
oc create secret generic config-quay \
  --from-file=config.yaml=quay-tng/config.yaml \
  --from-file=ssl.cert=/opt/certs/wildcard.crt \
  --from-file=ssl.key=/opt/certs/wildcard.key \
  --dry-run=client -o yaml | oc apply -f -
```
and I have set the ``SERVER_HOSTNAME`` key in the config.yaml file.

Here is the QuayRegistry:

```yaml
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: skynet
spec:
  configBundleSecret: config-quay
  components:
    - kind: objectstorage
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
```

I did not find any other information regarding this issue, and I have zero customization on Clair component. I have this issue even when recreating the namespace from scratch, leaving no object behind.

Context: OpenShift 4.6.6
Tried with Operator Catalog Source a32ebc1d422c5285dacd9e97f2216be4a9aa8f06d20034909e4dba7f4b136004 and 71427cafa14a2ede270bf4525cd7d3a06945530fb48efa9300bac982ae8446ea

Any help would be highly appreciated :)
