### ISSUE TITLE
using credentialsSecretName breaks deployment

### ISSUE THREAD

**Issue by itewk** [quay/quay-operator#40]
when I specify a custom `credentialsSecretName` the operator fails to deploy the DB.

operator logs:

```
"level":"error","ts":1565109241.4033964,"logger":"controller_quayecosystem","msg":"Failed to Setup Quay","error":"database Validation Failed: FATAL:  password authentication failed for user \"quay\"\n","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem.(*ReconcileQuayEcosystem).Reconcile\n\t/home/travis/gopath/src/github.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/quayecosystem_controller.go:191\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1565109281.409356,"logger":"controller_quayecosystem","msg":"Reconciling QuayEcosystem","Request.Namespace":"quay-enterprise","Request.Name":"quay"}
```

secrete creation:
```
oc create secret generic quay-db-credential --from-literal=database-username=quay --from-literal=database-password=foobar --from-literal=database-root-password=foobar --from-literal=database-name=quay
```

quayechosystem definition:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay
spec:
  quay:
    imagePullSecretName: quayio-pull-secret
    superuserCredentialsSecretName: quay-superuser-credential
    configSecretName: quay-config-credential
    routeHost: quay.apps.example.com
    configRouteHost: quay-config.apps.example.com
    database:
      credentialsSecretName: quay-db-credential
      volumeSize: 10G
    registryStorage:
      persistentVolumeAccessMode:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi
```
