### ISSUE TITLE
Notifier service is disabled

### ISSUE THREAD

**Issue by shnplr** [quay/quay-operator#83]
quay.io/redhat-cop/quay-operator:v0.0.7
quay.io/redhat/clair-jwt:v3.1.0
The title message appears in the container log when clair is starting. I think clair/config.yaml could be changed:

```
--old--

updater:
  notifier:
    attempts: 1
    renotifyinterval: 1h0m0s
    http:
      endpoint: https://example.hostname.com/secscan/notify
      proxy: http://localhost:6063
  interval: 8h20m0s

--new--

updater:
  interval: 8h20m0s
notifier:
  attempts: 1
  renotifyinterval: 1h0m0s
  http:
    endpoint: https://example.hostname.com/secscan/notify
    proxy: http://localhost:6063
```
