### ISSUE TITLE
Unable to override matcher.period

### ISSUE THREAD

**Issue by roysjosh** [quay/quay-operator#834]
After installing quay 3.9.0 via the operator, it didn't take long to find my k8s cluster going crazy every 6h. I'm apparently hitting my full 40GbE line speed according to Grafana, and I have sustained 500MB/s disk RW. I run rook-ceph in-cluster, FYI. Also, it looks like each clair-app, of which there are two, does their own update leading to two spikes of activity, back to back.

I tried to turn down the update period from 6h to 10d (golang doesn't support the "d" suffix 😢) but found that the YAML isn't merged. When I set
```yaml
---
matcher:
  period: 240h
```

I ended up with a broken config:
```json
{"level":"error","component":"main","error":"service initialization failed: failed to initialize matcher: failed to create ConnPool: failed to connect to `host=/tmp user=nobody database=`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)","time":"2023-09-05T13:05:08Z","message":"fatal error"}
```

```yaml
auth:
    psk:
        iss:
            - quay
            - clairctl
        key: REDACTED
http_listen_addr: :8080
indexer:
    connstring: host=key-clair-postgres port=5432 dbname=postgres user=postgres password=postgres sslmode=disable pool_max_conns=33
    layer_scan_concurrency: 5
    migrations: true
    scanlock_retry: 10
log_level: info
matcher:
    period: 240h
metrics:
    name: prometheus
notifier:
    connstring: host=key-clair-postgres port=5432 dbname=postgres user=postgres password=postgres sslmode=disable pool_max_conns=33
    delivery_interval: 1m0s
    migrations: true
    poll_interval: 5m0s
    webhook: REDACTED
[...]
```

Attempting to specify the generated fields led to a different error:
```
  Warning  ConfigInvalid              4m44s (x6 over 5m17s)     quayregistry-controller  clairpostgres component marked as managed, but `configBundleSecret` contains required fields
```

Specified config:
```yaml
---
matcher:
  connstring: host=key-clair-postgres port=5432 dbname=postgres user=postgres password=postgres sslmode=disable pool_max_conns=33
  migrations: true
  period: 240h
```
