### ISSUE TITLE
Clair failed to create environment vars

### ISSUE THREAD

**Issue by shnplr** [quay/quay-operator#84]
quay.io/redhat-cop/quay-operator:v0.0.7
quay.io/redhat/clair-jwt:v3.1.0

I defined the CRD as follows but environment vars were not created in Clair deployment

```
  clair:
    enabled: true
    envVars:
      - name: HTTP_PROXY
        value: "http://proxy.example.com:80"
      - name: HTTPS_PROXY
        value: "http://proxy.example.com:80"
    ...
```
workaround is to manually add to Deployment
