### ISSUE TITLE
S3 as storage results in error deploying

### ISSUE THREAD

**Issue by dmhumph** [quay/quay-operator#90]
I am trying to deploy using S3 storage and I am receiving the following error when trying to deploy the cr:

$ oc create -f s3_cr.yaml
The QuayEcosystem "example-quayecosystem" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"redhatcop.redhat.io/v1alpha1", "kind":"QuayEcosystem", "metadata":map[string]interface {}{"creationTimestamp":"2019-11-06T21:33:31Z", "generation":1, "name":"example-quayecosystem", "namespace":"quay-enterprise", "uid":"1427b888-00dd-11ea-a98d-02dd80a8768f"}, "spec":map[string]interface {}{"quay":map[string]interface {}{"imagePullSecretName":"redhat-pull-secret", "registryStorage":[]interface {}{map[string]interface {}{"name":"s3", "s3":map[string]interface {}{"host":"hosthere", "s3_access_key":"accesskey", "s3_bucket":"quay", "s3_secret_key":"secret+key"}}}}}}: validation failure list:
spec.quay.registryStorage in body must be of type object: "array"

This is what my cr looks like:

apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    registryStorage:
      - name: s3
        s3:
          s3_bucket: quay
          s3_access_key: acceskey
          s3_secret_key: secret+key
          host: host

**Comment by kurtismullins** [comment]
@dmhumph It looks like a bit of the formatting of your cr was lost. Would you be to use a code block and paste it into there? Based on the error you shared, it might simply be an indentation issue.

**Comment by dmhumph** [comment]
Sorry about that here is the cr:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    registryStorage:
      - name: s3
        s3:
          s3_bucket: quay
          s3_access_key: acceskey
          s3_secret_key: secret+key
          host: host
```
